#!/bin/sh

docker run \
  -it \
  -u $(id -u):$(id -g) \
  --runtime nvidia \
  -p 8888:8888 \
  --rm \
  -v $(realpath .):/tf/notebooks \
  -v $(realpath .local):/.local \
  tensorflow/tensorflow:1.15.0-gpu-py3-jupyter
